### ISSUE TITLE
Adds support for property 'expression'

### ISSUE THREAD

**Issue by alanbchristie** [InformaticsMatters/data-manager-metadata#3]
A field may contain an `expression` property. If so the incoming field name should be replaced by the expanded (jinja2) expression if the corresponding 'variable' is found in the Job specification or the field should be silently ignored.

For example, the `smiles` field may contain the following: -

```yaml
smiles:
  type: string
  expression: '{{ smilesFieldName }}'
  description: Molecule SMILES
```

As the `expression` property exists, if the `smilesFieldName` can be found in the Job spec the field (`smiles`) should be replaced by the expanded value of `{{ smilesFieldName }}`. if expansion fails the field should not be written
